# --- 博客信息 --------------------------------------------------------
blog_name: 乌鸦之家
blog_signature: '乌鸦的碎碎念'
author: "乌鸦"
footer_note: © 2025 乌鸦之家

# cc: "by-nc-nd"          # 版权声明
cc: false

# ignore_prefix: "IGNORE_"

# --- 博客构建器相关 --------------------------------------------------------------
# 目录配置
md_dir: "md/"
html_dir: "html/"
template_dir: "template/"
partials_dir: "partials/"

# --- 页面配置 ----------------------------------------------------------

# 链接信息
nav:
    - label: '首页'
      url: 'index.html'
    - label: '分类'
      url: 'NOCHECK_category.html'
    - label: '时光轴'
      url: 'NOCHECK_timeline.html'
    - label: 'RSS订阅'
      url: 'https://code-pigeon.github.io/blog/feed'

# --- 页面配置 ----------------------------------------------------------
# 基本
auto_h1: true           # 自动生成标题h1标签
has_comment: true       # 评论
has_toc: true           # 目录
# add_to_category: true   # 添加至“分类”页面？
# add_to_timeline: true   # 添加至“时间轴”页面？
private: false          # 私有（不提交至GitHub）
# html_name             # 这个会在生成html的过程中添加
# content               # 这个会在生成html的过程中添加

template: 'post.mustache'   # 默认模板

# markdown解析扩展
md_parser_extension: ['fenced_code', 'tables', 'footnotes', 'nl2br', 'pymdownx.tilde', 'pymdownx.tasklist']

# 互联网相关
img_url:    "../media/image/article/"                                                 # 图床
img_url2:   "https://pub-026ecfceb63744219eb65ba54fa5359f.r2.dev/"              # 备用图床
site: "https://code-pigeon.github.io/blog/"     # 博客基址
js_url:     '../js/'
css_url:    '../css/'
html_url:   


# --- 扩展管理 ----------------------------------------------------------
# 扩展开关
extensions:
    category: null
    timeline: null
    rss: {}

# --- timeline ----------------------------------------------------------
timeline_template: "timeline.mustache"


# --- category ----------------------------------------------------------
category_template: "category.mustache"